// Generated by LiveScript 1.3.1
$(document).ready(function(){
  var imgs, shadow, shadowImage;
  imgs = Array.from(document.querySelectorAll('.reveal'));
  shadow = document.createElement('div');
  shadowImage = document.createElement('div');
  shadow.setAttribute('class', 'reveal-shadow');
  document.body.appendChild(shadow);
  shadow.appendChild(shadowImage);
  shadow.addEventListener('click', function(){
    return import$(import$(shadow.style, shadow.source), {
      opacity: 0,
      zIndex: -1
    });
  });
  Array.from(document.querySelectorAll('.lightbox')).map(function(img){
    return img.addEventListener('click', function(){
      var box;
      box = img.getBoundingClientRect();
      shadow.setAttribute('class', 'reveal-shadow');
      shadow.box = box;
      shadow.source = {
        width: box.width + "px",
        height: box.height + "px",
        top: box.top + "px",
        left: box.left + "px",
        zIndex: 9999
      };
      import$(shadow.style, shadow.source);
      shadowImage.style.backgroundImage = "url(" + (img.getAttribute('data-lg-src') || img.getAttribute('data-src')) + ")";
      return setTimeout(function(){
        shadow.setAttribute('class', 'reveal-shadow active');
        return import$(shadow.style, {
          width: "100%",
          height: "100%",
          top: "0",
          left: "0",
          opacity: 1
        });
      }, 10);
    });
  });
  return window.addEventListener('scroll', function(){
    var h, y;
    h = window.innerHeight;
    y = window.pageYOffset;
    return imgs.map(function(img){
      var top;
      top = img.getBoundingClientRect().top;
      if (top < h && !img.revealed) {
        img.revealed = true;
        img.node = new Image();
        img.node.onload = function(){
          return setTimeout(function(){
            var cls;
            img.style.backgroundImage = "url(" + (img.getAttribute('data-src') || '') + ")";
            cls = img.getAttribute('class').split(' ');
            if (!~cls.indexOf('on')) {
              cls.push('on');
            }
            return img.setAttribute('class', cls.join(' '));
          }, Math.random() * 200);
        };
        return img.node.src = img.getAttribute('data-src') || '';
      }
    });
  });
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}