// Generated by LiveScript 1.3.1
$(document).ready(function(){
  var imgs;
  imgs = Array.from(document.querySelectorAll('.reveal'));
  imgs.map(function(img){
    img.node = new Image();
    return img.node.src = img.getAttribute('data-src');
  });
  return window.addEventListener('scroll', function(){
    var h, y;
    h = window.innerHeight;
    y = window.pageYOffset;
    return imgs.map(function(img){
      var top;
      top = img.getBoundingClientRect().top;
      if (top < h) {
        img.style.backgroundImage = "url(" + img.getAttribute('data-src') + ")";
        return img.style.backgroundSize = "contain";
      }
    });
  });
});